name: profile-service
namespace: namespace2
description: Profile management service for the core platform
environment:
    GO_ENV: development
    SERVICE_NAME: profile-service

scripts:
    build: true
    clean: false
    format: true
    lint: true
    test: true
    tidy: true
tags:
    - go
    - namespace2
    - microservice
 
dependencies:
  - "packages/go/common"