
description: Event handling service for the core platform
environment:
    GO_ENV: development
    SERVICE_NAME: event-service
name: event-service
namespace: namespace1
scripts:
    build: true
    format: true
    lint: true
    test: true
    tidy: true
tags:
    - go
    - namespace1
    - microservice

dependencies:
  - "packages/go/common"
  - "packages/go/httputils"