---
name: event-service
namespace: core-events
description: "Event handling service for the core platform"
dependencies: []
tags:
  - go
  - events
  - microservice
scripts:
  build: true
  test: true
  lint: true
  tidy: true
  format: true
  clean: false  # Disabled for this project
environment:
  GO_ENV: "development"
  SERVICE_NAME: "event-service"